- hosts: localhost
  vars:
  remote_user: root

  tasks:
    - name: Add wheel group
      group: name=wheel state=present
    - name: Add user for automation
      user: name=ansible group=wheel generate_ssh_key=yes
    - debug: msg="Add your public key to /home/ansible/.ssh/authorized_keys, if you don't you'll 
    lose access when you secure the server"