---
- hosts: newserver
  vars:
  remote_user: root

  vars_prompt:

  - name: "new_password"
    prompt: "Enter password for automation user"
    private: yes
    encrypt: "sha512_crypt"
    confirm: yes
    salt_size: 7

  tasks:
    - name: Install libselinux-python
      yum: name=libselinux-python state=present
    - name: Add wheel group
      group: name=wheel state=present
    - name: Add user for automation
      user: name=auto group=wheel password='{{ new_password }}'
    - name: Create .ssh directory for user
      file: path=/home/auto/.ssh state=directory
    - name: Copy across public key
      copy: src=/home/auto/.ssh/id_rsa.pub dest=/home/auto/.ssh/authorized_keys  owner=auto mode=0644
    - name: Add %wheel to sudoers
      lineinfile: dest=/etc/sudoers state=present regexp='^wheel ALL\=' line='wheel ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'
      notify:
         - restart sshd
  handlers:
       - name: restart sshd
         service: name=sshd state=restarted

