
    - name: SSH | get iptables rules
      shell: iptables -L
      register: iptablesrules
      always_run: yes
      changed_when: false
      sudo: yes

    - name: SSH | add table ssh input rule
      command: '/sbin/iptables -I INPUT 1 -p tcp --dport ssh -j ACCEPT -m comment --comment "SSH"'
      when: iptablesrules.stdout.find("SSH") == -1
      notify: ['save iptables','restart iptables']
      sudo: yes

    - name: DHCP | add table dhcp output rule
      command: '/sbin/iptables -A OUTPUT -p UDP --dport 67:68 -j ACCEPT -m comment --comment "DHCP"'
      when: iptablesrules.stdout.find("DHCP") == -1
      notify: ['save iptables','restart iptables']
      sudo: yes

    - name: DNS | add table dns output rule
      command: '/sbin/iptables -A OUTPUT -p udp --dport 53 -j ACCEPT -m comment --comment "DNS"'
      when: iptablesrules.stdout.find("DNS") == -1
      notify: ['save iptables','restart iptables']
      sudo: yes
      
    - name: SSH | add table drop input rule
      command: '/sbin/iptables -P INPUT DROP -m comment --comment "Drop input"'
      when: iptablesrules.stdout.find("Chain INPUT (policy DROP)") == -1  
      notify: ['save iptables','restart iptables']
      sudo: yes


    - name: SSH | add table drop forward rule
      command: '/sbin/iptables -P FORWARD DROP -m comment --comment "Drop forward"'
      when: iptablesrules.stdout.find("Chain FORWARD (policy DROP)") == -1
      notify: ['save iptables','restart iptables']
      sudo: yes


    - name: SSH | add table accept output rule
      command: '/sbin/iptables -P OUTPUT ACCEPT -m comment --comment "Accept output"'
      when: iptablesrules.stdout.find("Chain OUTPUT (policy ACCEPT)") == -1
      notify: ['save iptables','restart iptables']
      sudo: yes

    - name: SSH | add table accept local rule
      command: /sbin/iptables -A INPUT -i lo -j ACCEPT -m comment --comment "Accept local"
      when: iptablesrules.stdout.find("Accept local") == -1
      notify: ['save iptables','restart iptables']
      sudo: yes


    - name: SSH | add table accept establised rule
      command: /sbin/iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT -m comment --comment "Accept established"
      when: iptablesrules.stdout.find("Accept established") == -1
      notify: ['save iptables','restart iptables']
      sudo: yes

