    - name: Install ntp
      yum: name=ntp state=present
      sudo: yes

    - name: Add ntp pool 0
      lineinfile: dest=/etc/ntp.conf regexp="^server 0" line="server 0.asia.pool.ntp.org"
      sudo: yes
      notify:
         - restart ntp


    - name: Add ntp pool 1
      lineinfile: dest=/etc/ntp.conf regexp="^server 1" line="server 1.asia.pool.ntp.org"
      sudo: yes
      notify:
         - restart ntp


    - name: Add ntp pool 2
      lineinfile: dest=/etc/ntp.conf regexp="^server 2" line="server 2.asia.pool.ntp.org"
      sudo: yes
      notify:
         - restart ntp


    - name: Add ntp pool 3
      lineinfile: dest=/etc/ntp.conf regexp="^server 3" line="server 3.asia.pool.ntp.org"
      sudo: yes
      notify:
         - restart ntp
