
- name: ensure dnsmasq is installed
  yum: name=dnsmasq state=present
  sudo: yes

- name: Never forward addresses in the non-routed address spaces
  lineinfile: dest=/etc/dnsmasq.conf state=present regexp='^#bogus-priv' line='bogus-priv'
  sudo: yes

- name: Google DNS 1
  lineinfile: dest=/etc/dnsmasq.conf state=present regexp='^server=8.8.4.4' line='server=8.8.4.4'
  sudo: yes

- name: Google DNS 2
  lineinfile: dest=/etc/dnsmasq.conf state=present regexp='^server=8.8.8.8' line='server=8.8.8.8'
  sudo: yes

- name: Set local domain name
  lineinfile: dest=/etc/dnsmasq.conf state=present regexp='^#local=' line='local=/vm/'
  sudo: yes

- name: Only serve eth0
  lineinfile: dest=/etc/dnsmasq.conf state=present regexp='#interface=' line='interface=eth0'
  sudo: yes

- name: Expand hosts to include domain name
  lineinfile: dest=/etc/dnsmasq.conf state=present regexp='^#expand-hosts=' line='expand-hosts'
  sudo: yes

- name: Set domain
  lineinfile: dest=/etc/dnsmasq.conf state=present regexp='^#domain=' line='domain=vm'
  sudo: yes

- name: Set DHCP range
  lineinfile: dest=/etc/dnsmasq.conf state=present regexp='^#dhcp-range=' line='dhcp-range=10.1.2.103,10.1.2.254,12h'
  sudo: yes

- name: DNS | add table dns input rule
  command: '/sbin/iptables -I INPUT -p udp --dport 53 -j ACCEPT -m comment --comment "DNS_INPUT"'
  when: iptablesrules.stdout.find("DNS_INPUT") == -1
  notify: ['save iptables','restart iptables']
  sudo: yes

- name: DHCP | add table dhcp input rule
  command: '/sbin/iptables -I INPUT -p udp --dport 67:68 -j ACCEPT -m comment --comment "DHCP_INPUT"'
  when: iptablesrules.stdout.find("DNS_INPUT") == -1
  notify: ['save iptables','restart iptables']
  sudo: yes

- name: ensure dnsmasq starts on a fresh boot
  service: name=dnsmasq state=started enabled=yes
  sudo: yes

- name: Set DNS resolv.conf
  template: src=./templates/resolv.conf.j2 dest=/etc/resolv.conf mode=u=rw,g=r,o=r
  sudo: yes
  notify:
        - restart network
